### ISSUE TITLE
HTTP/HTTPS Redirect for Knative Serving Route

### ISSUE THREAD

**Issue by ultraJeff** [RHEcosystemAppEng/RAG-Blueprint#49]
Hey y'all,

I'm not sure where to add this in the code, otherwise I'd make a PR.

I tried installing this today on a two-GPU cluster and discovered an issue.

The Llamastack deployment was unable to reach the /models endpoint of the LLM hosted with Knative Serving. I futzed about with it for a while and discovered that adding the following YAML to the KnativeServing CR fixed the http/https redirect issue. Not sure if or how others are able to connect to it out of the box, but I needed this to fix the routes to work correctly.

```yaml
# in knative-serving
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
...
spec:
  config:
    network:
      httpProtocol: redirected
```
